app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_events/', views.get_events, name='get_events'),
    path('get_orgs/', views.get_orgs, name='get_orgs'),
    path('submit_facebook_event/', views.submit_facebook_event, name='submit_facebook_event'),
    path('pfe/', views.pending_facebook_events, name='pending_facebook_events'),
    path('event_post/', views.event_post, name='event_post')
]

kinesis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('badmin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Animal Activism PDX</title>

    <!-- https://materializecss.com/ -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <!-- https://vuejs.org/ -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

    <!-- https://github.com/axios/axios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>




    <style>
        * {
            box-sizing: border-box;
        }
        body {
            font-family: 'Open Sans', sans-serif;
            scroll-behavior: smooth;
        }
        #title_long {
            display:none;
            white-space: nowrap;
        }
        #title_short {
            white-space: nowrap;
        }
        @media only screen and (min-width: 800px) {
            #maincontainer {
                width:800px;
                margin:0 auto;
            }
            #title_short {
                display: none;
            }
            #title_long {
                display:inherit;
            }
        }


    </style>

</head>
<body class="green lighten-4">
    <div id="maincontainer">
        <nav class="green">
            <div class="nav-wrapper">
                <a href="/" id="title_short" class="brand-logo center">AAPDX</a>
                <a href="/" id="title_long" class="brand-logo center">Animal Activism PDX</a>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
    <script>
        let symbols = {
            // 'leaf_left': '☙',
            // 'flower': '⚘',
            'seedling': '🌱',
            'evergreen_tree': '🌲',
            'deciduous_tree': '🌳',
            // 'palm_tree': '🌴',
            'cactus': '🌵',
            // 'tulip': '🌷',
            // 'cherry_blossom': '🌸',
            'rose': '🌹',
            // 'hibiscus': '🌺',
            'sunflower': '🌻',
            // 'blossom': '🌼',
            'herb': '🌿',
            'four_leaf_clover': '🍀',
            'maple_leaf': '🍁',
            'fallen_leaf': '🍂',
            // //'leaf_fluttering_in_wind': '🍃',
            // 'tomato': '🍅',
            // 'aubergine': '🍆',
            // 'grapes': '🍇',
            // 'melon': '🍈',
            // 'watermelon': '🍉',
            // 'tangerine': '🍊',
            // 'lemon': '🍋',
            // 'banana': '🍌',
            // 'pineapple': '🍍',
            // 'red_apple': '🍎',
            // 'green_apple': '🍏',
            // 'pear': '🍐',
            // 'peach': '🍑',
            // 'cherries': '🍒',
            // 'strawberry': '🍓',
            // //'boquet': '💐',
            // 'white_flower': '💮',

            // 'white chess knight': '♘',
            // 'black chess knight': '♞',
            'rat': '🐀',
            'mouse': '🐁',
            'ox': '🐂',
            'water buffalo': '🐃',
            'cow': '🐄',
            'tiger': '🐅',
            'leopard': '🐆',
            'rabbit': '🐇',
            'cat': '🐈',
            //'dragon': '🐉',
            'crocodile': '🐊',
            'whale': '🐋',
            'snail': '🐌',
            'snake': '🐍',
            'horse': '🐎',
            'ram': '🐏',
            'goat': '🐐',
            'sheep': '🐑',
            'monkey': '🐒',
            'rooster': '🐓',
            'chicken': '🐔',
            'dog': '🐕',
            'pig': '🐖',
            'boar': '🐗',
            'elephant': '🐘',
            'octopus': '🐙',
            'spiral shell': '🐚',
            'bug': '🐛',
            'ant': '🐜',
            'honeybee': '🐝',
            'lady beetle': '🐞',
            'fish': '🐟',
            'tropical fish': '🐠',
            'blowfish': '🐡',
            'turtle': '🐢',
            'hatching chick': '🐣',
            'baby chick': '🐤',
            'front-facing baby chick': '🐥',
            'bird': '🐦',
            'penguin': '🐧',
            'koala': '🐨',
            'poodle': '🐩',
            'dromedary camel': '🐪',
            'bactrian camel': '🐫',
            'dolphin': '🐬',
            'mouse face': '🐭',
            'cow face': '🐮',
            'tiger face': '🐯',
            'rabbit face': '🐰',
            'cat face': '🐱',
            //'dragon face': '🐲',
            'spouting whale': '🐳',
            'horse face': '🐴',
            'monkey face': '🐵',
            'dog face': '🐶',
            'pig face': '🐷',
            'frog face': '🐸',
            'hamster face': '🐹',
            'wolf face': '🐺',
            'bear face': '🐻',
            'panda face': '🐼',
            'pig nose': '🐽',
            'paw prints': '🐾',
            //'grinning cat face with smiling eyes': '😸',
            //'cat face with tears of joy': '😹',
            //'smiling cat face with open mouth': '😺',
            //'smiling cat face with heart-shaped eyes': '😻',
            //'cat face with wry smile': '😼',
            //'kissing cat face with closed eyes': '😽',
            //'pouting cat face': '😾',
            //'crying cat face': '😿',
            //'weary cat face': '🙀',
            'see-no-evil monkey': '🙈',
            'speak-no-evil monkey': '🙊',
            'hear-no-evil monkey': '🙉',

        }

        let title_short = document.querySelector('#title_short')
        let title_long = document.querySelector('#title_long')

        let keys = Object.keys(symbols)
        let symbol = symbols[keys[Math.floor(keys.length * Math.random())]];
        title_short.innerHTML = symbol + ' AAPDX ' + symbol
        title_long.innerHTML = symbol + ' Animal Activism PDX ' + symbol


        // test code
        // let i = 0
        // setInterval(function() {
        //     let keys = Object.keys(symbols)
        //     let symbol = symbols[keys[i%keys.length]]
        //     i += 1
        //     title_short.innerHTML = symbol + ' PAA ' + symbol
        //     title_long.innerHTML = symbol + 'Portland Animal Activism' + symbol
        // }, 1000)

    </script>
</body>
</html>

app/templates/app/event_post.html
{% extends 'app/base.html' %}

{% block content %}
<style>
    textarea {
        background-color:white;
        height: 400px;
        padding:10px;
    }

    #formdiv {
        padding:10px;
        margin:10px 0px;
        text-align:center;
    }

</style>
<div id="formdiv" class="white z-depth-2 row">
    <form action="" method="post">
        {% csrf_token %}
        <div class="input-field inline">
            <select name="week_index" class="inline">
                {% for week in weeks %}
                <option value="{{week.index}}" {% if week.index == week_index %}selected{% endif %}>{{week.name}}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn">view events</button>
    </form>
</div>
<textarea>
View all upcoming events on http://aapdx.org!
{% for event in events %}
{{event.title}}
{{event.datetime}}
{{event.location}}
{{event.link}}
{% endfor %}

</textarea>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems, {});
    });
</script>

{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}




{% block content %}

<style>
    #event_list {
      display:flex;
      flex-direction:column;
      margin:0 auto;
    }
    #event_list > div {
      margin-top:20px;
      transition: all ease 0.2s;
      /*box-shadow: 0px 2px 2px lightgrey;*/
      cursor:pointer;
    }

    #event_list ul {
      margin:0;
    }

    .event_title {
      font-size:24px;
    }

    #pages > span {
      margin:4px;
      cursor:pointer;
      padding:4px;
    }

    .collapsible-header {
      display:flex;
      flex-direction: column;
    }

    .list_element > li {
      margin:0 0 20px 0 !important;
      width:100% !important;
    }


    @media only screen and (min-width: 800px) {
        #filters {
            display:flex;
            flex-direction: row;
            width:100%;
        }
        #filters > div {
            width:33%;
            padding:10px;
        }
    }

    .pagination {
        text-align:center;
    }

    .list_element li.active i {
      -ms-transform: rotate(180deg); /* IE 9 */
      -webkit-transform: rotate(180deg); /* Chrome, Safari, Opera */
      transform: rotate(180deg);
    }


    /* .event_expand_bt {
      display:table;
      height:100%;
    }
    .event_expand_bt > * {
      text-align:right;
      vertical-align: middle;
      display:table-cell;
    } */

    .event_expand_bt i {
      margin:0;
    }

    .flex_column {
      display:flex;
      flex-direction:column;
    }

    /* #filters select, #filters input {
      background-color:white;
      padding:8px;
      color:black;
    } */


    #filters > div {
      background-color:white;
      margin:4px;
    }


</style>
<div id="app">

    <div id="event_list">
        {% comment %}
        <div id="filters">
          <div class="input-field col s6">
            <select id="type" v-model="filter_type" @change="page=1; refresh()">
                <option value="events" selected>Events</option>
                <option value="organizations">Organizations</option>
            </select>
          </div>
          <div class="input-field col s6">
            <select v-model="filter_category_id" @change="page=1; refresh()">
                <option value="0">Any</option>
                {% for category in categories %}
                <option value="{{category.id}}">{{category.name.title}}</option>
                {% endfor %}
            </select>
          </div>
          <div class="input-field col s6" v-show="filter_type == 'events'">
            <input placeholder="" id="first_name" type="date" v-model="filter_start_date" @change="refresh">
          </div>

        </div>
        {% endcomment %}
        <div v-if="filter_type == 'events'">
          <div style="text-align:center" v-if="events.length == 0" class="white">no events to display</div>
          <ul class="collapsible popout list_element">
              <li v-for="event in events" class="white">
                  <div class="collapsible-header">
                      <div style="display:flex;flex-direction:row;justify-content: space-between;">
                          <div class="flex_column">
                              <div class="event_title">[[event.title]]</div>
                              <div v-if="event.organizations != ''">Hosted by [[event.hosts]]</div>
                              <div>[[event.datetime]]</div>
                              <div>[[event.location]]</div>
                          </div>
                          <div class="flex_column" style="justify-content: space-between;">
                            <div v-if="event.link != ''" class="event_expand_bt">
                                <a class="btn green white-text" v-bind:href="event.link" target="_blank">
                                    <i class="material-icons">link</i>
                                </a>
                            </div>
                            <div class="event_expand_bt" style="">
                                <div class="btn green white-text">
                                    <i class="material-icons">expand_more</i>
                                </div>
                            </div>
                          </div>
                      </div>
                  </div>
                  <div class="collapsible-body">
                      <span v-html="event.description"></span>
                  </div>
              </li>
          </ul>
        </div>
        <div v-if="filter_type == 'organizations'">
          <div style="text-align:center" v-if="orgs.length == 0" class="white">no organizations to display</div>
          <ul class="list_element">
              <li v-for="org in orgs" class="white">
                  <div class="collapsible-header">
                      <div style="display:flex;flex-direction:row;justify-content: space-between;">
                          <div class="flex_column">
                              <div class="event_title">[[org.name]]</div>
                              <div>[[org.address]]</div>
                              <div>[[org.phone_number]]</div>
                              <div>[[org.email_address]]</div>
                          </div>
                          <div class="flex_column" style="justify-content: center;">
                            <div v-if="org.url != ''" class="event_expand_bt">
                                <a class="btn green white-text" v-bind:href="org.url" target="_blank">
                                    <i class="material-icons">link</i>
                                </a>
                            </div>
                          </div>
                      </div>
                  </div>
              </li>
          </ul>
        </div>
        </div>

        <ul class="pagination" v-show="pages > 1">
            <li v-bind:class="{ disabled: page == 0 }"><a href="#" @click="prevPage"><i class="material-icons">chevron_left</i></a></li>
            <li v-for="n in pages" v-bind:class="{active: (page == n), green: (page == n) }"><a href="#" @click="setPage(n)">[[n]]</a></li>
            <li><a href="#" @click="nextPage"><i class="material-icons">chevron_right</i></a></li>
        </ul>
    </div>
</div>
<script>





    document.addEventListener('DOMContentLoaded', function () {
        var ddls = document.querySelectorAll('select')
        var ddl_instances = M.FormSelect.init(ddls, {})

        var uls = document.querySelectorAll('.collapsible');
        var ul_instances = M.Collapsible.init(uls, {});
    });

    let app = new Vue({
        el: '#app',
        delimiters: ['[[', ']]'],
        data: {
            events: [],
            orgs: [],
            pages: 0,
            page: 1,
            filter_type: 'events',
            filter_start_date: null,
            filter_category_id: 0,
        },
        methods: {
            prevPage: function() {
                if (this.page > 1) {
                    this.page -= 1
                    this.refresh()
                }
            },
            nextPage: function() {
                if (this.page < this.pages) {
                    this.page += 1
                    this.refresh()
                }
            },
            setPage: function(n) {
                this.page = n
                this.refresh()
            },
            refresh: function() {
              if (this.filter_type == 'events') {
                this.loadEvents()
              } else {
                this.loadOrgs()
              }
            },
            loadEvents: function() {
                axios.get('/get_events/', {
                    params: {
                        'page': this.page,
                        'start_date': this.filter_start_date,
                        'category_id': this.filter_category_id
                    }
                }).then(result => {
                    this.events = result.data.events
                    this.pages = result.data.pages
                    window.scrollTo(0, 0);
                })
            },
            loadOrgs: function() {
              axios.get('/get_orgs/', {
                params: {
                    'page': this.page,
                    'category_id': this.filter_category_id
                }
              }).then(result => {
                  this.orgs = result.data.orgs
                  this.pages = result.data.pages
                  window.scrollTo(0, 0);
              })
            }
        },
        created: function() {

            var now = new Date()
            var day = ('0' + now.getDate()).slice(-2)
            var month = ('0' + (now.getMonth() + 1)).slice(-2)
            var today = now.getFullYear()+'-'+(month)+'-'+(day)
            this.filter_start_date = today

            this.refresh()
        }
    })

</script>


{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}


{% block content %}
{% if message %}
<span style="background-color:green;color:white;font-size:40px">{{message}}</span>
{% endif %}


<style>
    form {
        width:400px;
        margin: 40px auto;
    }
    button {
        margin-top:10px;
    }
</style>




<form action="{% url 'app:login' %}?next={{next}}" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input id="username" type="text" name="username" placeholder=""/>
    <label for="password">Password</label>
    <input id="password" type="password" name="password" placeholder=""/>
    <button type="submit" class="btn blue">login</button>
</form>





{% endblock %}

app/templates/app/pending_facebook_events.html
{% extends 'app/base.html' %}

{% block content %}
{% if message %}
<div class="message blue white-text z-depth-2">{{message}}</div>
{% endif %}

<style>
    .row {
        padding: 10px;
        margin:10px;
    }
    .message {
        margin: 10px;
        padding:10px;
        text-align:center;
        cursor: default;
    }
</style>

<div class="white z-depth-2 row">
    <form action="{% url 'app:pending_facebook_events' %}?action=add" method="post" class="col s12">
        {% csrf_token %}
        <div class="input-field inline" style="width:80%">
            <input placeholder="https://www.facebook.com/events/1789125017772768/" id="facebook_url" type="text" name="facebook_url" pattern="https:\/\/www\.facebook\.com\/events\/\d+\/"/>
            <label for="facebook_url">Facebook Event URL</label>
        </div>
        <button type="submit" class="btn">Add</button>
    </form>

</div>

<div class="white z-depth-2 row">
    <form action="{% url 'app:pending_facebook_events' %}?action=load" method="post">
        {% csrf_token %}
        <button type="submit" class="btn">Load All</button>
    </form>
    <br/>
    <ul>
    {% for pending_event in pending_events %}
        <li><a target="_blank" href="{{pending_event.url}}">{{pending_event.url}}</a></li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

app/templates/app/submit_facebook_event.html
{% extends 'app/base.html' %}


{% block content %}

<script src='https://www.google.com/recaptcha/api.js'></script>

<style>
    #maindiv {
        margin:10px;
        padding:10px;
    }
    .message {
        margin: 10px;
        padding:10px;
        text-align:center;
        cursor: default;
    }
</style>

{% if message_error %}
<div class="message red white-text z-depth-2">{{message_error}}</div>
{% endif %}


{% if message_success %}
<div class="message blue white-text z-depth-2">{{message_success}}</div>
{% endif %}

<div id="maindiv" class="white z-depth-2 row">
    <form action="{% url 'app:submit_facebook_event' %}" method="post" class="col s12">
        {% csrf_token %}
        <div class="input-field">
            <input placeholder="https://www.facebook.com/events/1789125017772768/" id="facebook_url" type="text" name="facebook_url"/>
            <label for="facebook_url">Facebook Event URL</label>
        </div>
        <div class="input-field">
        <div class="g-recaptcha" data-sitekey="6LckvWoUAAAAABQ-E8kuah1rCyar70tikKStMQWz"></div>
        </div>
        <button type="submit" class="btn">Submit</button>
    </form>
</div>

{% endblock %}

app/templates/app/user.html
{% extends 'app/base.html' %}


{% block content %}
<div class="row">
    <form class="col s12">
        <div class="row">
            <div class="input-field col s6">
                <input placeholder="" id="first_name" type="text" class="validate">
                <label for="first_name">First Name</label>
            </div>
            <div class="input-field col s6">
                <input id="last_name" type="text" class="validate">
                <label for="last_name">Last Name</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input disabled value="I am not editable" id="disabled" type="text" class="validate">
                <label for="disabled">Disabled</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input id="password" type="password" class="validate">
                <label for="password">Password</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input id="email" type="email" class="validate">
                <label for="email">Email</label>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                This is an inline input field:
                <div class="input-field inline">
                    <input id="email_inline" type="email" class="validate">
                    <label for="email_inline">Email</label>
                    <span class="helper-text" data-error="wrong" data-success="right">Helper text</span>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/templates/app/view_event.html
{% extends 'app/base.html' %}

{% block content %}






{% endblock %}